version: "3"
services:
  hootsman:
    build: .
    image: valderman/hootsman:latest
    container_name: hootsman
    restart: unless-stopped
    ports:
      - "127.0.0.1:8080:8080"
    volumes:
      - /opt/hootsman:/data
